name: mang_ga_no_ni
description: "생성형 AI mang_ga_no_ni를 이용한 자기소개서 생성/관리 프로그램"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #google_mobile_ads: ^5.0.0
  #app_tracking_transparency: ^2.0.5

  shared_preferences: ^2.2.3

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  provider: ^6.1.2
  go_router: ^6.2.0
  webview_flutter: ^4.7.0
  percent_indicator: ^4.2.3
  intl: ^0.19.0
  uuid: ^4.4.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: bongodicBold
      fonts:
        - asset: assets/fonts/NotoSansKR-Bold.ttf
    - family: bongodicExtraBold
      fonts:
        - asset: assets/fonts/NotoSansKR-ExtraBold.ttf
    - family: bongodicMedium
      fonts:
        - asset: assets/fonts/NotoSansKR-Medium.ttf
    - family: bongodicRegular
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf